; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
debug_tool = stlink
lib_deps = 
    ; z3t0/IRremote@^3.9.0
    https://github.com/adafruit/Adafruit_VL53L0X.git
    https://github.com/Arduino-IRremote/Arduino-IRremote.git
upload_flags =
    -c
    set CPUTAPID 0x2ba01477
build_flags = -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
              -I config
monitor_port = /dev/ttyACM0
monitor_speed = 115200
